<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Successfuly-Added</name>
   <tag></tag>
   <elementGuidId>dfb18085-5609-424d-9eeb-4d8448c317bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[normalize-space()='successfully']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
